server:
  port: 811
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chao
    password: 123456
    url: jdbc:mysql://mysql.bzchao.com:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最大激活数
      max-active: 50
      # 最大等待时间
      max-wait: 3000
      # 是否启用非公平锁
      use-unfair-lock: true
      # mysql 用 false | oracle 用 true
      pool-prepared-statements: false

swagger:
  enable: true
  tokenName: Authorization
